import { config, library } from '@fortawesome/fontawesome-svg-core';
import {
  faWindows,
  faLinux,
  faApple,
  faJs,
} from '@fortawesome/free-brands-svg-icons';
import {
  faStar,
  faSwatchbook,
  faShieldCheck,
  faFolderTree,
  faMindShare,
  faCommentLines,
  faLongArrowAltLeft,
  faSparkles,
  faFolder,
  faFolderOpen,
  faExternalLink,
  faCalendarEdit,
  faHighlighter,
  faCog,
  faChevronDown,
  faUser,
  faEdit,
  faBringFront,
  faUsersClass,
  faMicrochip,
} from '@fortawesome/pro-solid-svg-icons';

config.autoAddCss = false;

library.add(
  faWindows,
  faLinux,
  faApple,
  faJs,
  faStar,
  faSwatchbook,
  faShieldCheck,
  faFolderTree,
  faMindShare,
  faCommentLines,
  faLongArrowAltLeft,
  faSparkles,
  faFolder,
  faFolderOpen,
  faExternalLink,
  faCalendarEdit,
  faHighlighter,
  faCog,
  faChevronDown,
  faUser,
  faEdit,
  faBringFront,
  faUsersClass,
  faMicrochip,
);
